apiVersion: v1
kind: Service
metadata:
  name: mysite-app-service-svc
  namespace: mysite-app
  labels:
    application: mysite-app
spec:
  type: ClusterIP
  selector:
    app: mysite-app

  ports:
  - name: http
    port: 8080
    targetPort: 80


