apiVersion: v1
kind: ConfigMap
metadata:
  name: site-configmap
data:
  APP: mysite
  MYSQL_HOST: registration-app-mysql.apis-services.cluster.local
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: root
  MYSQL_PASSWORD: rootpassword
  MYSQL_DATABASE: mysite_db
